[package]
name = "hola_mundo"
version = "0.1.1"
edition = "2021"
description = "A binary crate to test an upload to crates.io"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
